<?php 


?>
<!DOCTYPE html>
<html lang="en">

<head>
    <title>PHP homework</title>
    <meta name="keywords" content=" jacob, web development homework">
    <meta name="Author:" value="Jacob Scroggins">
    <meta name="destription" content="homework ">
    <meta charset="UTF-8">
    <meta name="viewprt" content="width=device-width, initial-scale=1.0">

    
    <style>

    </style>

    <script>
    
    </script>

</head>

<body >
    <p>Version control software is a tool that helps manage changes to  code or other types of files over time. It  also allows multiple people to work on the same code simultaneously while keeping track of every modification made</p>

    <p>Add: This command stages changes to be included in the next commit. </p>

    <p>Commit: This command saves your staged changes to the local repository with a descriptive message. </p>

    <p>Push: This command uploads your local commits to a remote repository, making your changes available to others. </p>

    <p>Pull: This command fetches and integrates changes from a remote repository into your local repository.</p>

    <p>Clone: This command creates a copy of an existing remote repository on your local machine. It not only downloads the repository but also sets up a connection to the remote repository so you can pull updates and push changes.</p>

</body>

</html>